Basic UI implementation
mhawryluk/data-mining-tool pull request #1
Opened 2022-04-18 17:55 UTC by mhawryluk

Implemented the basic UI structure, based on the concept by @gregori0o

Not ideal, a lot needs improvement:
* the window and widgets are fixed sized and position
* an animation for unfolding widgets would be nice
* maybe a flexbox could be used
* visually it's not great

2022-04-18 19:09 UTC, t0ms0n00 commented
Flexbox can be done without using any library. QHBoxLayout's method _addWidget_ has a parameter **stretch** (int). It is used to scale added element in layout relatively to others, i.e. if we had elements Button1, Button2, Button3 and set stretch property to 1, 3, 1 in sequence, we would receive a box in which first button would take 20% of container width, Button2 next 60% and Button3 last 20%. **What is important**, every element in the layout **should have that property set to 1 or more** . In the other way, element will have fixed size. Default stretch value is 0.

Example:

```
self.groupBox = QGroupBox("What is your name?")
hboxlayout = QHBoxLayout()
button = QPushButton("name1")
button.setMinimumHeight(40)
hboxlayout.addWidget(button, stretch=1)
button2 = QPushButton("name2")
button2.setMinimumHeight(40)
hboxlayout.addWidget(button2, stretch=3)
self.groupBox.setLayout(hboxlayout)
```

Above solution also should resolve issue with fixed window size, now we can fit it to user's screen.

2022-04-19 08:57 UTC, gregori0o approved these changes
It's good basic implementation. This code is good skeleton of our app.
My suggestion is to change method of import. If we decide to import in `__init__.py` files we must change import lines in other files, which I didn't mark.

2022-04-19 08:57 UTC, gregori0o commented on src/widgets/main_widget.py
> +from widgets.visualization_widget import VisualizationWidget
It is good idea to split each class into files.
I think we can simplify imports from widgets package by adding imports in file [\_\_init\_\_.py](src/widgets/__init__.py).
```suggestion
from widgets import AlgorithmWidget, ImportWidget, PreprocessingWidget, VisualizationWidget
```
My suggestion is to change [\_\_init\_\_.py](src/widgets/__init__.py) file. I write my proposition of code in next comment.

2022-04-19 08:57 UTC, gregori0o commented on src/widgets/__init__.py
> +UNFOLD_WIDGET_WIDTH = WINDOW_WIDTH - 3*UNFOLD_BUTTON_WIDTH - 20
I want to imports classes in this file so I suggest coping this lines to the new `data.py` file and add imports in `__init__.py` file.
```suggestion
from .data import WINDOW_HEIGHT, WINDOW_WIDTH, UNFOLD_BUTTON_WIDTH, UNFOLD_WIDGET_WIDTH

from .unfold_widget import UnfoldWidget
from .algorithm_widget import AlgorithmWidget
from .import_widget import ImportWidget
from .preprocessing_widget import PreprocessingWidget
from .visualization_widget import VisualizationWidget
from .main_layout import MainWindow
```

2022-04-19 09:15 UTC, t0ms0n00 requested changes
Overally it is very good job, I've suggested some minor changes.

2022-04-19 09:15 UTC, t0maboro commented on src/widgets/algorithm_widget.py
> +        self.button.setStyleSheet("background-color: rgb(177, 221, 240);")
Maybe we should use external .css files for stylesheet? With more advanced styles it should be more readable that inline approach. It can be done with python's file-handle functions open() and read(). Then the stylesheets should be placed in some other directory i.e. static/css/ . 
*I wrote it only here but it's suggestion for all setStyleSheet() invocations.

2022-04-19 09:15 UTC, t0maboro commented on src/widgets/algorithm_widget.py
> +        self.button.setText("ALGORITHM")
Not an important thing, but rotating button text vertically can prevent us from text overflow when button width is shorter than text width (ofc if it is possible to do). Anyways, we may set different stretch properties dependable of screen width to avoid above problem.

2022-04-19 09:15 UTC, t0ms0n00 commented on src/widgets/main_widget.py
> +
This method probably should change mentioned in my comment stretch values dependable on button click and re-render.

2022-04-19 09:15 UTC, t0ms0n00 commented on src/widgets/algorithm_widget.py
> +        self.technique_box.addItem("associations")
Maybe some helper component that will handle selection with list of choices passed?

2022-04-20 22:40 UTC, merged