Results - cluster view
mhawryluk/data-mining-tool pull request #19
Opened 2022-05-29 22:11 UTC by t0ms0n00

Todo:
- [x] Preview cluster elements
- [x] Plot cluster instead of centroids when showing elements
- [ ] Save clusters to file

If you think that something in layout/logic should be done differently - let me know. 
To discuss: format of the file for saving cluster. Saving to csv should be done easily, but we might consider other formats, or leave a choice for users.

2022-05-30 22:36 UTC, mhawryluk requested changes
Looks great, I love the cluster selecting by double clicking on table row, brilliant! 
One thing that doesn't work yet is changing the axes on the chart while in the specific cluster view. It plots all the centroids again like it used to.

2022-05-30 22:36 UTC, mhawryluk commented on src/widgets/results_widgets/k_means_results.py
> +    def update_cluster_plot(self, row=None):
Maybe rename _row_ to _selected_label_ or _selected_cluster_

2022-05-30 22:36 UTC, mhawryluk commented on src/widgets/results_widgets/k_means_results.py
> +        path, is_ok = QInputDialog.getText(self, 'input name', 'Enter filename')
```suggestion
        path, is_ok = QInputDialog.getText(self, 'Save to file', 'Enter filename')
```

2022-05-30 22:36 UTC, mhawryluk commented on src/widgets/results_widgets/k_means_results.py
> +            error.exec_()
We shouldn't show an error when the user simply cancelled the window. I assume is_ok is False in that case. Also when the extension is wrong the error message should state that the file type is incorrect. The current message makes sense if there was indeed an exception while trying to create/access the file.

2022-05-31 16:17 UTC, gregori0o reviewed
That is very good idea to selecting cluster by double-click and show them in Centroids section.

There are some problems with message box and changing axis, which @mhawryluk mentioned.
I suggest add one more functionality. Button 'save result' or something like that, which save data to file with new column. In this column will be number of cluster for the row.

2022-06-06 15:52 UTC, mhawryluk approved these changes
Great, just a few tiny suggestions :)

2022-06-06 15:52 UTC, mhawryluk commented on src/widgets/results_widgets/k_means_results.py
> +            error.setText("No path were provided")
```suggestion
            error.setText("No path was provided")
```

2022-06-06 15:52 UTC, mhawryluk commented on src/widgets/results_widgets/k_means_results.py
> +                error.setText("Something wrong happened while was writing data to file. Try again")
```suggestion
                error.setText("Something wrong happened while writing data to file. Try again")
```

2022-06-06 15:52 UTC, mhawryluk commented on src/widgets/results_widgets/k_means_results.py
> +            self.selected_cluster = idx.row()
it seems as though this doesn't have to be a loop

2022-06-06 19:26 UTC, gregori0o approved these changes
❤️ 💪

2022-06-06 20:18 UTC, merged