Merging sets
mhawryluk/data-mining-tool pull request #31
Opened 2022-11-11 13:44 UTC by t0ms0n00

The general flow and the UI can be reviewed. I'll need to do some investigation about typing on the pandas .concat method.

2022-11-15 22:08 UTC, mhawryluk requested changes
Looks really good! I noticed a few bugs. 

Overall, it seems to work great when we want to concatenate two datasets with the same columns, just maybe differing in names. However if our two sets have a few common columns, but the rest is unrelated, the only good option currently is to first drop the uncommon columns before merging. There's no option to say that a certain column does not have its equivalent and that it should therefore be filled with null values in place of the new data. However, not saying that this option has to be there, especially considering how undesirable missing values are, so maybe it is best to leave it as is. just something to consider.

2022-11-15 22:08 UTC, mhawryluk commented on src/widgets/tables/merging_sets_screen.py
> +        for column in self.engine.get_columns():
this doesn't always work. when we unselect a column in the import view, it is still presented as one of the columns in this view and the program crashes at `reorder_columns`. I think columns need to be obtained in some other way

2022-11-15 22:08 UTC, mhawryluk commented on src/widgets/tables/merging_sets_screen.py
> +        for column in self.engine.get_columns():
maybe we could sort columns alphabetically here? then if both sets have the same column names we don't have to reorder anything. though sometimes we may want to preserve the original order (e.g. groceries_crosstab should have memeber_index as first). so the best solution would be to sort the new columns matching them to the old ones if they have the same name. but it seems not that important now that I think about it, so idk

2022-11-15 22:08 UTC, mhawryluk commented on src/widgets/tables/merging_sets_screen.py
> +    def _load_from_file_handle(self):
maybe these methods could be moved to a common super class, so there's no repeated code. maybe after the refactor pr is merged into develop, this could be improved accordingly, if there is time and it's even possible

2022-11-15 22:08 UTC, mhawryluk commented on src/widgets/tables/merging_sets_screen.py
> +                    if pos.y() < w.mapToGlobal(w.rect().topLeft()).y() - self.pos().y():
crashes when we drop a widget below the lowest one, `w` is None then I think

2022-11-19 21:03 UTC, gregori0o reviewed
Very nice UI of data merging.

I think we don't need droping column without pairs, because we can do it in import widget by selecting columns. Maybe we should fill lack column with nulls. I have one idea how add possibilty to tell that some column don't have a pair. I think about add button with trash, which allow remove column from merging (and fill this column with nulls after merging).
![image](https://user-images.githubusercontent.com/72767517/202871469-2b2e7afd-e3a3-47ea-8542-f11e2f81f21d.png)

2022-11-19 21:03 UTC, gregori0o commented on src/widgets/tables/merging_sets_screen.py
> +        for column in self.engine.get_columns():
+1, it is good idea to write some heuristics about sorting column but it is not the most important thing

2022-11-19 21:03 UTC, gregori0o commented on src/widgets/tables/merging_sets_screen.py
> +    def _load_from_file_handle(self):
you can create a component with data loading and inform this class and import widget about loading data by signals

2022-12-03 22:26 UTC, gregori0o reviewed
I like the merging panel. It looks and works nice.
I found one bug, so I want to report this and I will continue review tomorrow.

I have one thing to consider. For me, it should work in this way: if I remove columns in merging panel, I won't lost them, but I will have this column with nulls for second dataset. Example:
![image](https://user-images.githubusercontent.com/72767517/205464590-6145a9ae-88b5-495a-9cb0-124567c849ce.png)

Tip: `pd.concat` automatically adds `NaN` for missing columns.

2022-12-03 22:26 UTC, gregori0o commented on src/widgets/tables/merging_sets_screen.py
> +        labels_right = new_columns_right[:num_columns]
When I tried merge two dataset with iris (in the second I remove 3 columns) I got error. You should add something like this in this place:
`self.new_data = self.new_data[labels_right]`

2022-12-04 19:42 UTC, mhawryluk commented
>

2022-12-04 20:03 UTC, mhawryluk commented on src/widgets/tables/merging_sets_screen.py
> +            new_column_name = f"Column {i}"
when there are more columns on the right than on the left, the columns have these generic names after merging. can't we instead use the names of the actual columns from the right (`new_columns_right[i+...])`? we could add some sort of unique identifier to the end to make it more likely to be unique if that's the problem

2022-12-04 20:08 UTC, mhawryluk commented
> I have one thing to consider. For me, it should work in this way: if I remove columns in merging panel, I won't lost them, but I will have this column with nulls for second dataset. @mhawryluk what do you think about this?

I agree. would be cool if it worked like that

2022-12-10 16:07 UTC, mhawryluk approved these changes
LGTM! Great job 😀

2022-12-10 16:19 UTC, gregori0o approved these changes
Perfect!

2022-12-10 16:19 UTC, gregori0o commented on src/widgets/tables/merging_sets_screen.py
> +        icon = self.style().standardIcon(pixmapi)
```suggestion
        pixmap = getattr(QStyle, "SP_DialogCancelButton")
        icon = self.style().standardIcon(pixmap)
```
typo

2022-12-10 16:19 UTC, gregori0o commented on src/widgets/tables/merging_sets_screen.py
> +
```suggestion
        for i in reversed(range(self.columns_right_layout.count() - 1)):
            self.columns_right_layout.itemAt(i).widget().setParent(None)

```
Imported data doesn't change, so I think we can leave left layout as it is.

2022-12-10 16:19 UTC, gregori0o commented on src/widgets/tables/merging_sets_screen.py
> +            self.new_data.rename(columns={column: new_column_name}, inplace=True)
```suggestion
        for column in dropped_columns + overflowed_columns:
            new_column_name = f"{column}_new"
            self.new_data.rename(columns={column: new_column_name}, inplace=True)
```

2022-12-10 17:06 UTC, merged